### ISSUE TITLE
Unhandled exception executing command 'bank' in plugin MineBank v4.0.1

### ISSUE THREAD

**Issue by christinloehner** [Guayand0/Minecraft-Plugin-MineBank#2]
Great plugin - until version 3.3.2. Unfortunatly the new version 4.0.1 throws errors over error. First, I just copied 4.0.1 into plugins folder of my bukkit-paper 1.21.1 and restarted. Then I saw, that I need to purge the MineBank folder, except bank.yml. I've done this. Then I got an error about wrong playerhead URL in playerinventory. I fixed that, by commenting out the older texture thing and activated the newer texture thing... and Now I get the following error and /bank is still unuseable:

```
[04:32:25] [Server thread/INFO]: ChristinGHG issued server command: /bank
[04:32:25] [Server thread/ERROR]: Command exception: /bank
org.bukkit.command.CommandException: Unhandled exception executing command 'bank' in plugin MineBank v4.0.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.substring(int, int)" because "topBankBankNameValue" is null
at MineBank-4.0.1.jar/mb.Guayando.utils.MethodUtils.replaceTopPlaceholders(MethodUtils.java:155) ~[MineBank-4.0.1.jar:?]
at MineBank-4.0.1.jar/mb.Guayando.utils.MethodUtils.replacePlaceholders(MethodUtils.java:114) ~[MineBank-4.0.1.jar:?]
at MineBank-4.0.1.jar/mb.Guayando.events.BankInventoryEvent.createItem(BankInventoryEvent.java:129) ~[MineBank-4.0.1.jar:?]
at MineBank-4.0.1.jar/mb.Guayando.events.BankInventoryEvent.loadItemsIntoInventory(BankInventoryEvent.java:99) ~[MineBank-4.0.1.jar:?]
at MineBank-4.0.1.jar/mb.Guayando.events.BankInventoryEvent.openBankInventory(BankInventoryEvent.java:75) ~[MineBank-4.0.1.jar:?]
at MineBank-4.0.1.jar/mb.Guayando.commands.ComandoBank.onCommand(ComandoBank.java:87) ~[MineBank-4.0.1.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
... 27 more

```

**Comment by Guayand0** [comment]
Fixed ;), thanks for reporting the bug

**Comment by Guayand0** [comment]
Fixed ;), thanks for reporting the bug
